-- AlterTable
ALTER TABLE "subscriptions" ADD COLUMN     "abandoned_checkout_email2_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "abandoned_checkout_email3_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "browse_abandon_email1_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "browse_abandon_email2_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "browse_abandon_email3_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "last_checkout_expired_at" TIMESTAMPTZ(6),
ADD COLUMN     "last_pricing_viewed_at" TIMESTAMPTZ(6),
ADD COLUMN     "post_upgrade_day3_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "post_upgrade_day7_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "renewal_1d_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "renewal_30d_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "renewal_7d_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "welcome_day2_sent" BOOLEAN DEFAULT false,
ADD COLUMN     "welcome_day5_sent" BOOLEAN DEFAULT false;
