// AUTO-GENERATED by coo-scripts/lib/seo_meta_fixer.py
// Generated: 2026-04-12T00:27:35.122076+01:00
// Drop this file in Lunary repo at: src/lib/monthly-meta-overrides.ts
// Then update src/lib/horoscope-meta.ts monthMeta() to check overrides first.

export type MonthlyMetaOverride = {
  title: string;
  description: string;
  titleVariantB?: string;
  descriptionVariantB?: string;
  faq?: { question: string; answer: string }[];
};

// Key format: `${signSlug}/${year}/${monthSlug}` (lowercase)
export const MONTHLY_META_OVERRIDES: Record<string, MonthlyMetaOverride> = {
  'virgo/2026/april': {
    title: 'Virgo April 2026 Horoscope: Mercury Trine Pluto & Money Moves',
    description:
      'Mercury trines Pluto on 16 April—expect financial shifts. Full Moon in Virgo brings clarity. Read your detailed April forecast now.',
    titleVariantB:
      'Virgo Horoscope April 2026: Full Moon Insights & Wealth Trends',
    descriptionVariantB:
      'Virgo’s Full Moon on 1 April highlights career and finances. Discover key dates and guidance. Tap for your April 2026 horoscope.',
    faq: [
      {
        question: 'What is the key transit for Virgo in April 2026?',
        answer:
          'Mercury trines Pluto on 16 April, boosting Virgo’s financial and communication prospects. This transit can bring transformative opportunities.',
      },
      {
        question: 'How will the Full Moon in Virgo affect me in April 2026?',
        answer:
          'The Full Moon in Virgo on 1 April brings clarity to personal goals and routines. It’s a good time for reflection and making practical changes.',
      },
      {
        question: 'What are the main themes for Virgo in April 2026?',
        answer:
          'Financial shifts, career insights, and personal transformation are highlighted. Mercury’s trine to Pluto and the Full Moon are key influences.',
      },
    ],
  },
  'gemini/2026/april': {
    title: 'Gemini April 2026: Venus Enters Gemini, Home Focus 24 Apr',
    description:
      'Venus enters Gemini 24 April, boosting family ties. Key dates: 5th, 18th, 24th. Discover your April 2026 Gemini horoscope now.',
    titleVariantB: 'Gemini April 2026 Horoscope: Venus Transit & Family Shifts',
    descriptionVariantB:
      "Venus in Gemini from 24 April brings home and relationship shifts. See Gemini's April 2026 forecast with key transit dates.",
    faq: [
      {
        question: 'When does Venus enter Gemini in April 2026?',
        answer:
          'Venus enters Gemini on 24 April 2026, marking a period of enhanced social and family connections for Geminis.',
      },
      {
        question:
          'What are the key astrological dates for Gemini in April 2026?',
        answer:
          'Important dates include 5 April (Mercury sextile Mars), 18 April (New Moon), and 24 April (Venus enters Gemini).',
      },
      {
        question: "How will April 2026 affect Gemini's home life?",
        answer:
          'April brings a focus on home and family, especially after Venus enters Gemini, supporting harmonious domestic changes.',
      },
    ],
  },
  'sagittarius/2026/april': {
    title: 'Sagittarius April 2026: Aries Season Fire & New Moon Boost',
    description:
      'Sagittarius, April 2026 brings Aries energy, a New Moon on 15 April, and lucky days 9-16 April. Discover your best moves for love and work.',
    titleVariantB:
      'Sagittarius Horoscope April 2026: New Moon Goals & Mars Shift',
    descriptionVariantB:
      'April 2026 for Sagittarius features a New Moon on 15 April and Mars entering Leo. Find your luckiest days and career tips now.',
    faq: [
      {
        question: 'What are the luckiest days for Sagittarius in April 2026?',
        answer:
          'Sagittarius luck peaks between 9 and 16 April, especially around the New Moon on 15 April. Plan key actions during this window.',
      },
      {
        question: 'How does Aries season affect Sagittarius in April 2026?',
        answer:
          "Aries season energises Sagittarius, boosting confidence and motivation. It's a strong time for setting new goals and taking bold steps.",
      },
      {
        question:
          'What major astrological events impact Sagittarius in April 2026?',
        answer:
          'The New Moon on 15 April and Mars shifting into Leo are key events, bringing fresh starts and creative energy for Sagittarius.',
      },
    ],
  },
};

export function getMonthlyMetaOverride(
  signSlug: string,
  year: string,
  monthSlug: string,
): MonthlyMetaOverride | undefined {
  return MONTHLY_META_OVERRIDES[`${signSlug}/${year}/${monthSlug}`];
}
