export const correspondencesData = {
  elements: {
    Fire: {
      colors: ['Red', 'Orange', 'Gold'],
      crystals: ['Carnelian', 'Red Jasper', 'Citrine', 'Sunstone'],
      herbs: ['Cinnamon', 'Ginger', 'Basil', 'Clove'],
      planets: ['Sun', 'Mars'],
      days: ['Sunday', 'Tuesday'],
      zodiacSigns: ['Aries', 'Leo', 'Sagittarius'],
      numbers: [1, 3],
      animals: ['Lion', 'Salamander', 'Phoenix'],
      directions: 'South',
      seasons: 'Summer',
      timeOfDay: 'Noon',
    },
    Water: {
      colors: ['Blue', 'Silver', 'Sea Green', 'Teal'],
      crystals: ['Moonstone', 'Aquamarine', 'Rose Quartz', 'Pearl'],
      herbs: ['Jasmine', 'Rose', 'Chamomile', 'Seaweed'],
      planets: ['Moon', 'Neptune'],
      days: ['Monday'],
      zodiacSigns: ['Cancer', 'Scorpio', 'Pisces'],
      numbers: [2, 7],
      animals: ['Dolphin', 'Seal', 'Whale'],
      directions: 'West',
      seasons: 'Autumn',
      timeOfDay: 'Dusk',
    },
    Air: {
      colors: ['Yellow', 'White', 'Pale Blue', 'Sky Blue'],
      crystals: ['Clear Quartz', 'Fluorite', 'Lapis Lazuli', 'Amethyst'],
      herbs: ['Lavender', 'Mint', 'Frankincense', 'Eucalyptus'],
      planets: ['Mercury', 'Uranus'],
      days: ['Wednesday'],
      zodiacSigns: ['Gemini', 'Libra', 'Aquarius'],
      numbers: [3, 8],
      animals: ['Eagle', 'Butterfly', 'Bird'],
      directions: 'East',
      seasons: 'Spring',
      timeOfDay: 'Dawn',
    },
    Earth: {
      colors: ['Green', 'Brown', 'Black', 'Tan'],
      crystals: ['Hematite', 'Green Aventurine', 'Black Tourmaline', 'Jade'],
      herbs: ['Sage', 'Cedar', 'Patchouli', 'Oak'],
      planets: ['Saturn', 'Venus'],
      days: ['Saturday', 'Friday'],
      zodiacSigns: ['Taurus', 'Virgo', 'Capricorn'],
      numbers: [4, 6],
      animals: ['Bear', 'Stag', 'Ox'],
      directions: 'North',
      seasons: 'Winter',
      timeOfDay: 'Midnight',
    },
  },
  colors: {
    Red: {
      correspondences: ['Fire', 'Passion', 'Strength', 'Courage', 'Love'],
      uses: ['Protection', 'Love spells', 'Courage', 'Power'],
      planets: ['Mars', 'Sun'],
    },
    Orange: {
      correspondences: ['Fire', 'Creativity', 'Joy', 'Success'],
      uses: ['Manifestation', 'Creativity', 'Success'],
      planets: ['Sun'],
    },
    Yellow: {
      correspondences: ['Air', 'Intellect', 'Communication', 'Learning'],
      uses: ['Mental clarity', 'Communication', 'Learning'],
      planets: ['Mercury', 'Sun'],
    },
    Green: {
      correspondences: ['Earth', 'Growth', 'Prosperity', 'Healing'],
      uses: ['Money spells', 'Healing', 'Growth', 'Prosperity'],
      planets: ['Venus'],
    },
    Blue: {
      correspondences: ['Water', 'Peace', 'Healing', 'Protection'],
      uses: ['Healing', 'Peace', 'Protection', 'Psychic ability'],
      planets: ['Neptune', 'Moon'],
    },
    Purple: {
      correspondences: ['Spirit', 'Magic', 'Wisdom', 'Psychic ability'],
      uses: ['Psychic work', 'Spirituality', 'Protection'],
      planets: ['Neptune', 'Jupiter'],
    },
    White: {
      correspondences: ['Purity', 'Protection', 'Spirit', 'All elements'],
      uses: ['Purification', 'Protection', 'Spirituality'],
      planets: ['Moon'],
    },
    Black: {
      correspondences: [
        'Protection',
        'Banishing',
        'Absorption',
        'Transformation',
      ],
      uses: ['Protection', 'Banishing', 'Absorbing negativity'],
      planets: ['Saturn'],
    },
    Pink: {
      correspondences: [
        'Love',
        'Friendship',
        'Compassion',
        'Emotional healing',
      ],
      uses: ['Love spells', 'Friendship', 'Self-love'],
      planets: ['Venus'],
    },
    Silver: {
      correspondences: [
        'Moon',
        'Intuition',
        'Feminine energy',
        'Psychic ability',
      ],
      uses: ['Psychic work', 'Intuition', 'Lunar magic'],
      planets: ['Moon'],
    },
    Gold: {
      correspondences: ['Sun', 'Prosperity', 'Success', 'Divine energy'],
      uses: ['Prosperity', 'Success', 'Solar magic'],
      planets: ['Sun'],
    },
  },
  days: {
    Monday: {
      planet: 'Moon',
      element: 'Water',
      correspondences: ['Intuition', 'Emotions', 'Dreams', 'Feminine energy'],
      uses: ['Emotional healing', 'Dream work', 'Intuition', "Women's magic"],
    },
    Tuesday: {
      planet: 'Mars',
      element: 'Fire',
      correspondences: ['Courage', 'Action', 'Strength', 'Passion'],
      uses: ['Protection', 'Courage', 'Action', 'Banishing'],
    },
    Wednesday: {
      planet: 'Mercury',
      element: 'Air',
      correspondences: ['Communication', 'Learning', 'Travel', 'Mercury'],
      uses: ['Communication', 'Learning', 'Travel', 'Mental clarity'],
    },
    Thursday: {
      planet: 'Jupiter',
      element: 'Fire',
      correspondences: ['Prosperity', 'Expansion', 'Luck', 'Growth'],
      uses: ['Prosperity', 'Abundance', 'Luck', 'Expansion'],
    },
    Friday: {
      planet: 'Venus',
      element: 'Earth',
      correspondences: ['Love', 'Beauty', 'Relationships', 'Creativity'],
      uses: ['Love spells', 'Beauty', 'Relationships', 'Creativity'],
    },
    Saturday: {
      planet: 'Saturn',
      element: 'Earth',
      correspondences: ['Protection', 'Banishing', 'Karma', 'Discipline'],
      uses: ['Protection', 'Banishing', 'Karma work', 'Discipline'],
    },
    Sunday: {
      planet: 'Sun',
      element: 'Fire',
      correspondences: ['Success', 'Prosperity', 'Strength', 'Vitality'],
      uses: ['Success', 'Prosperity', 'Strength', 'Solar magic'],
    },
  },
  deities: {
    Greek: {
      Aphrodite: { domain: ['Love', 'Beauty', 'Relationships'] },
      Apollo: { domain: ['Sun', 'Music', 'Healing', 'Prophecy'] },
      Artemis: { domain: ['Moon', 'Hunting', 'Wilderness', 'Protection'] },
      Athena: { domain: ['Wisdom', 'War', 'Crafts', 'Strategy'] },
      Demeter: { domain: ['Harvest', 'Agriculture', 'Motherhood'] },
      Dionysus: { domain: ['Wine', 'Ecstasy', 'Theater', 'Transformation'] },
      Hecate: { domain: ['Magic', 'Crossroads', 'Protection', 'Necromancy'] },
      Hermes: { domain: ['Communication', 'Travel', 'Commerce', 'Magic'] },
      Hades: { domain: ['Underworld', 'Death', 'Wealth', 'Transformation'] },
      Hera: { domain: ['Marriage', 'Family', 'Protection'] },
      Persephone: { domain: ['Spring', 'Death', 'Rebirth', 'Underworld'] },
      Poseidon: { domain: ['Sea', 'Water', 'Horses', 'Earthquakes'] },
      Zeus: { domain: ['Sky', 'Thunder', 'Justice', 'Kingship'] },
    },
    Norse: {
      Freyja: { domain: ['Love', 'Fertility', 'War', 'Magic'] },
      Frigg: { domain: ['Marriage', 'Motherhood', 'Wisdom', 'Protection'] },
      Loki: { domain: ['Trickery', 'Fire', 'Transformation', 'Chaos'] },
      Odin: { domain: ['Wisdom', 'War', 'Magic', 'Poetry'] },
      Thor: { domain: ['Thunder', 'Protection', 'Strength', 'Oak trees'] },
      Tyr: { domain: ['War', 'Justice', 'Courage', 'Law'] },
    },
    Egyptian: {
      Anubis: { domain: ['Death', 'Mummification', 'Protection', 'Guide'] },
      Bastet: { domain: ['Protection', 'Cats', 'Fertility', 'Joy'] },
      Isis: { domain: ['Magic', 'Healing', 'Protection', 'Motherhood'] },
      Osiris: { domain: ['Death', 'Rebirth', 'Agriculture', 'Underworld'] },
      Ra: { domain: ['Sun', 'Creation', 'Life', 'Kingship'] },
      Thoth: { domain: ['Wisdom', 'Writing', 'Magic', 'Moon'] },
    },
  },
  flowers: {
    Rose: {
      correspondences: ['Love', 'Beauty', 'Heart', 'Emotions'],
      colors: ['Red', 'Pink', 'White'],
      planets: ['Venus'],
      uses: ['Love spells', 'Beauty', 'Emotional healing'],
    },
    Lavender: {
      correspondences: ['Peace', 'Sleep', 'Purification', 'Protection'],
      colors: ['Purple'],
      planets: ['Mercury'],
      uses: ['Sleep', 'Purification', 'Peace', 'Protection'],
    },
    Jasmine: {
      correspondences: ['Love', 'Dreams', 'Psychic ability', 'Moon'],
      colors: ['White'],
      planets: ['Moon'],
      uses: ['Love spells', 'Dream work', 'Psychic ability'],
    },
    Sunflower: {
      correspondences: ['Sun', 'Prosperity', 'Happiness', 'Success'],
      colors: ['Yellow', 'Gold'],
      planets: ['Sun'],
      uses: ['Prosperity', 'Happiness', 'Success'],
    },
    Lily: {
      correspondences: ['Purity', 'Protection', 'Rebirth', 'Spirituality'],
      colors: ['White'],
      planets: ['Moon'],
      uses: ['Purification', 'Protection', 'Spirituality'],
    },
  },
  numbers: {
    1: {
      correspondences: ['Unity', 'Beginnings', 'Independence', 'Sun'],
      planets: ['Sun'],
      uses: ['New beginnings', 'Manifestation', 'Independence'],
    },
    2: {
      correspondences: ['Duality', 'Balance', 'Partnership', 'Moon'],
      planets: ['Moon'],
      uses: ['Partnerships', 'Balance', 'Intuition'],
    },
    3: {
      correspondences: ['Creativity', 'Expression', 'Trinity', 'Jupiter'],
      planets: ['Jupiter'],
      uses: ['Creativity', 'Expression', 'Growth'],
    },
    4: {
      correspondences: ['Stability', 'Foundation', 'Earth', 'Saturn'],
      planets: ['Saturn'],
      uses: ['Stability', 'Foundation', 'Protection'],
    },
    5: {
      correspondences: ['Change', 'Freedom', 'Adventure', 'Mercury'],
      planets: ['Mercury'],
      uses: ['Change', 'Communication', 'Travel'],
    },
    6: {
      correspondences: ['Harmony', 'Love', 'Beauty', 'Venus'],
      planets: ['Venus'],
      uses: ['Love', 'Harmony', 'Beauty'],
    },
    7: {
      correspondences: ['Magic', 'Mystery', 'Spirituality', 'Neptune'],
      planets: ['Neptune'],
      uses: ['Magic', 'Spirituality', 'Mystery'],
    },
    8: {
      correspondences: ['Infinity', 'Power', 'Abundance', 'Saturn'],
      planets: ['Saturn'],
      uses: ['Prosperity', 'Power', 'Abundance'],
    },
    9: {
      correspondences: ['Completion', 'Wisdom', 'Karma', 'Mars'],
      planets: ['Mars'],
      uses: ['Completion', 'Wisdom', 'Karma'],
    },
  },
  wood: {
    Oak: {
      correspondences: ['Strength', 'Protection', 'Endurance', 'Thunder'],
      uses: ['Protection', 'Strength', 'Endurance'],
      planets: ['Sun', 'Jupiter'],
    },
    Willow: {
      correspondences: ['Moon', 'Intuition', 'Emotions', 'Dreams'],
      uses: ['Intuition', 'Dream work', 'Emotional healing'],
      planets: ['Moon'],
    },
    Ash: {
      correspondences: ['Protection', 'Prosperity', 'Health', 'Sea'],
      uses: ['Protection', 'Prosperity', 'Health'],
      planets: ['Sun', 'Neptune'],
    },
    Birch: {
      correspondences: [
        'New beginnings',
        'Purification',
        'Protection',
        'Youth',
      ],
      uses: ['New beginnings', 'Purification', 'Protection'],
      planets: ['Venus'],
    },
    Cedar: {
      correspondences: ['Protection', 'Purification', 'Prosperity', 'Healing'],
      uses: ['Protection', 'Purification', 'Prosperity'],
      planets: ['Sun'],
    },
  },
  herbs: {
    Sage: {
      correspondences: ['Purification', 'Wisdom', 'Protection', 'Longevity'],
      uses: ['Smudging', 'Purification', 'Protection', 'Wisdom'],
      planets: ['Jupiter'],
    },
    Rosemary: {
      correspondences: ['Memory', 'Protection', 'Purification', 'Love'],
      uses: ['Protection', 'Memory', 'Purification'],
      planets: ['Sun'],
    },
    Basil: {
      correspondences: ['Protection', 'Prosperity', 'Love', 'Peace'],
      uses: ['Protection', 'Prosperity', 'Love'],
      planets: ['Mars'],
    },
    Lavender: {
      correspondences: ['Peace', 'Sleep', 'Purification', 'Protection'],
      uses: ['Sleep', 'Peace', 'Purification', 'Protection'],
      planets: ['Mercury'],
    },
    Cinnamon: {
      correspondences: ['Prosperity', 'Protection', 'Love', 'Success'],
      uses: ['Prosperity', 'Protection', 'Love', 'Success'],
      planets: ['Sun'],
    },
    Thyme: {
      correspondences: ['Courage', 'Purification', 'Health', 'Sleep'],
      uses: ['Courage', 'Purification', 'Health'],
      planets: ['Venus'],
    },
    Mint: {
      correspondences: ['Prosperity', 'Protection', 'Healing', 'Travel'],
      uses: ['Prosperity', 'Protection', 'Healing'],
      planets: ['Venus'],
    },
    Rose: {
      correspondences: ['Love', 'Beauty', 'Healing', 'Protection'],
      uses: ['Love spells', 'Beauty', 'Healing'],
      planets: ['Venus'],
    },
  },
  animals: {
    Cat: {
      correspondences: ['Protection', 'Mystery', 'Intuition', 'Moon'],
      uses: ['Protection', 'Intuition', 'Psychic ability'],
      planets: ['Moon'],
    },
    Owl: {
      correspondences: ['Wisdom', 'Intuition', 'Mystery', 'Night'],
      uses: ['Wisdom', 'Intuition', 'Mystery'],
      planets: ['Moon'],
    },
    Wolf: {
      correspondences: ['Loyalty', 'Protection', 'Intuition', 'Pack'],
      uses: ['Protection', 'Loyalty', 'Intuition'],
      planets: ['Moon'],
    },
    Raven: {
      correspondences: ['Magic', 'Transformation', 'Mystery', 'Death'],
      uses: ['Magic', 'Transformation', 'Mystery'],
      planets: ['Saturn'],
    },
    Snake: {
      correspondences: ['Transformation', 'Healing', 'Rebirth', 'Wisdom'],
      uses: ['Transformation', 'Healing', 'Rebirth'],
      planets: ['Mercury', 'Pluto'],
    },
    Bear: {
      correspondences: ['Strength', 'Protection', 'Healing', 'Dreams'],
      uses: ['Strength', 'Protection', 'Healing'],
      planets: ['Mars'],
    },
    Butterfly: {
      correspondences: ['Transformation', 'Beauty', 'Soul', 'Rebirth'],
      uses: ['Transformation', 'Beauty', 'Rebirth'],
      planets: ['Mercury'],
    },
    Horse: {
      correspondences: ['Power', 'Freedom', 'Travel', 'Strength'],
      uses: ['Power', 'Freedom', 'Travel'],
      planets: ['Mars', 'Neptune'],
    },
  },
};
