import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

const OPEN_WEBUI_URL = 'http://localhost:8080';
const OPEN_WEBUI_API_KEY =
  process.env.OPEN_WEBUI_API_KEY ||
  'sk-9074640fcf7dd8f3e702bc2e7ce74a9e011b31992357c0684c4fc8a671e32e4e';
const OPEN_WEBUI_BRAIN_KB_ID = '0d2ca384-e2aa-4ca0-af6c-4d83d1a31d4a';

interface FunnelData {
  freeUsersL30d: number;
  trialSignups: number;
  trialConversionRate: number;
  paidUsers: number;
  paidConversionRate: number;
  avgDaysToTrial: number;
  avgDaysTrialToPaid: number;
  timestamp: string;
}

async function getFunnelData(): Promise<FunnelData> {
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

  const freeUsersL30d = await prisma.subscriptions.count({
    where: { status: 'free', created_at: { gte: thirtyDaysAgo } },
  });

  const trialUsers = await prisma.subscriptions.findMany({
    where: { status: 'trial', created_at: { gte: thirtyDaysAgo } },
    select: { created_at: true },
  });

  const paidUsers = await prisma.subscriptions.count({
    where: { is_paying: true },
  });

  const trialConversionRate =
    freeUsersL30d > 0 ? (trialUsers.length / freeUsersL30d) * 100 : 0;
  const paidConversionRate =
    trialUsers.length > 0 ? (paidUsers / trialUsers.length) * 100 : 0;

  const avgDaysToTrial = 3;
  const avgDaysTrialToPaid = 7;

  return {
    freeUsersL30d,
    trialSignups: trialUsers.length,
    trialConversionRate: Number(trialConversionRate.toFixed(2)),
    paidUsers,
    paidConversionRate: Number(paidConversionRate.toFixed(2)),
    avgDaysToTrial,
    avgDaysTrialToPaid,
    timestamp: new Date().toISOString(),
  };
}

async function analyzeWithLocalModel(funnelData: FunnelData): Promise<string> {
  try {
    // Use OpenAI-compatible API endpoint for Open WebUI
    const response = await fetch(`${OPEN_WEBUI_URL}/api/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${OPEN_WEBUI_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'analytics-brain', // Use analytics-brain agent
        messages: [
          {
            role: 'user',
            content: `Analyze this Lunary funnel data and provide actionable insights for acquisition & activation:

Free users (30d): ${funnelData.freeUsersL30d}
Trial signups (30d): ${funnelData.trialSignups}
Free→Trial conversion: ${funnelData.trialConversionRate.toFixed(1)}%
Paid users: ${funnelData.paidUsers}
Trial→Paid conversion: ${funnelData.paidConversionRate.toFixed(1)}%

For EACH conversion stage:
1. Is it a bottleneck? (compare to 15% free→trial, 12% trial→paid benchmarks)
2. What's the root cause?
3. What ONE test would move the needle most?
4. What's the expected impact?

Format as structured insights, not prose.`,
          },
        ],
        temperature: 0.7,
        max_tokens: 1500,
      }),
    });

    if (!response.ok) {
      throw new Error(`Open WebUI error: ${response.statusText}`);
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content || '';
  } catch (error) {
    console.error('Failed to call local model:', error);
    throw error;
  }
}

async function storeInKnowledgeBase(
  analysis: string,
  funnelData: FunnelData,
): Promise<void> {
  try {
    const docContent = `# Activation Intelligence Weekly Report
Generated: ${funnelData.timestamp}

## Funnel Metrics
- Free users (30d): ${funnelData.freeUsersL30d}
- Trial signups: ${funnelData.trialSignups}
- Free→Trial rate: ${funnelData.trialConversionRate.toFixed(1)}%
- Paid users: ${funnelData.paidUsers}
- Trial→Paid rate: ${funnelData.paidConversionRate.toFixed(1)}%

## AI Analysis
${analysis}

---
*This report was generated by the Activation Intelligence cron job and analyzed using local LLM reasoning.*`;

    // Store in Sammii Brain KB via Open WebUI
    const uploadResponse = await fetch(
      `${OPEN_WEBUI_URL}/api/v1/documents/add`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${OPEN_WEBUI_API_KEY}`,
        },
        body: JSON.stringify({
          title: `Activation Report ${new Date(funnelData.timestamp).toISOString().split('T')[0]}`,
          content: docContent,
          collection_name: 'Sammii Brain',
          metadata: {
            type: 'activation-intelligence',
            week: new Date(funnelData.timestamp).toISOString().split('T')[0],
          },
        }),
      },
    );

    if (!uploadResponse.ok) {
      console.warn('Failed to store in KB:', await uploadResponse.text());
      // Non-fatal — continue anyway
    }
  } catch (error) {
    console.error('Failed to store in knowledge base:', error);
    // Non-fatal
  }
}

async function storeRecommendationsInDB(analysis: string): Promise<void> {
  // Parse AI insights and store structured recommendations
  const recommendations = [
    {
      recommendation:
        analysis.split('\n')[0] || 'See analysis in knowledge base',
      category: 'strategy' as const,
      priority: 'high' as const,
      generated_by: 'local-llm-analytics-brain',
      metadata: { full_analysis: analysis },
    },
  ];

  // Clear old ones
  await prisma.activation_recommendations.updateMany({
    where: {
      status: 'active',
      generated_at: { lt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
    },
    data: { status: 'archived' },
  });

  for (const rec of recommendations) {
    await prisma.activation_recommendations.create({
      data: {
        recommendation: rec.recommendation,
        category: rec.category,
        priority: rec.priority,
        status: 'active',
        generated_by: rec.generated_by,
        metadata: rec.metadata,
      },
    });
  }
}

export async function GET(req: Request) {
  // Verify Vercel cron secret
  const authHeader = req.headers.get('authorization');
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    console.log('[Activation Intelligence] Starting weekly analysis...');

    // 1. Get funnel data
    const funnelData = await getFunnelData();
    console.log('[Activation Intelligence] Funnel data:', funnelData);

    // 2. Send to local LLM for reasoning
    const analysis = await analyzeWithLocalModel(funnelData);
    console.log('[Activation Intelligence] Analysis complete');

    // 3. Store findings in knowledge base
    await storeInKnowledgeBase(analysis, funnelData);
    console.log('[Activation Intelligence] Stored in knowledge base');

    // 4. Store recommendations in DB
    await storeRecommendationsInDB(analysis);
    console.log('[Activation Intelligence] Stored recommendations in DB');

    return NextResponse.json({
      success: true,
      message: 'Activation intelligence analysis complete',
      metrics: {
        freeUsersL30d: funnelData.freeUsersL30d,
        trialConversionRate: funnelData.trialConversionRate,
        paidConversionRate: funnelData.paidConversionRate,
      },
      analysisLength: analysis.length,
    });
  } catch (error) {
    console.error('[Activation Intelligence] Error:', error);
    return NextResponse.json(
      {
        error: 'Activation intelligence analysis failed',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    );
  }
}
