import transitData from '../../src/data/slow-planet-sign-changes.json';

// Average daily motion (degrees per day)
export const PLANET_DAILY_MOTION = {
  Moon: 13.176, // 27.3 days to orbit
  Sun: 0.9856, // 365.25 days
  Mercury: 4.092, // 88 days
  Venus: 1.602, // 225 days
  Mars: 0.524, // 687 days
  Jupiter: 0.083, // 12 years
  Saturn: 0.034, // 29.5 years
  Uranus: 0.012, // 84 years
  Neptune: 0.006, // 165 years
  Pluto: 0.004, // 248 years
} as const;

// Slow planets that use ephemeris-computed sign changes
export const SLOW_PLANETS = ['Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'];

// Fast planets that use orbital speed calculations (Moon-Mars)
export const FAST_PLANETS = ['Moon', 'Sun', 'Mercury', 'Venus', 'Mars'];

export interface SignChangeDate {
  start: Date;
  end: Date;
  sign: string;
}

/**
 * Build a lookup: { planet: { sign: SignChangeDate[] } }
 * Reads from pre-computed JSON (generated by scripts/compute-transit-dates.ts).
 * No runtime astronomy-engine computation.
 */
function loadSlowPlanetSignChanges(): Record<
  string,
  Record<string, SignChangeDate[]>
> {
  const result: Record<string, Record<string, SignChangeDate[]>> = {};

  for (const [planet, signs] of Object.entries(transitData.segments)) {
    result[planet] = {};
    for (const [sign, segments] of Object.entries(
      signs as Record<string, { start: string; end: string }[]>,
    )) {
      result[planet][sign] = segments.map((seg) => ({
        start: new Date(seg.start),
        end: new Date(seg.end),
        sign,
      }));
    }
  }

  return result;
}

// Load from pre-computed JSON on module load
export const SLOW_PLANET_SIGN_CHANGES = loadSlowPlanetSignChanges();
