import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { BingAiPerformanceSnapshot } from './ai-performance';

const MANUAL_SEEDS = [
  {
    url: 'https://lunary.app/grimoire',
    path: '/grimoire',
    source: 'manual',
    reason: 'Core astrology knowledge hub for search and AI discovery.',
  },
  {
    url: 'https://lunary.app/grimoire/guides/birth-chart-complete-guide',
    path: '/grimoire/guides/birth-chart-complete-guide',
    source: 'manual',
    reason:
      'Deep evergreen birth chart guide with strong AI citation potential.',
  },
  {
    url: 'https://lunary.app/grimoire/guides/tarot-complete-guide',
    path: '/grimoire/guides/tarot-complete-guide',
    source: 'manual',
    reason: 'Deep evergreen tarot guide with strong AI citation potential.',
  },
  {
    url: 'https://lunary.app/grimoire/guides/moon-phases-guide',
    path: '/grimoire/guides/moon-phases-guide',
    source: 'manual',
    reason:
      'Deep evergreen moon phases guide with strong AI citation potential.',
  },
] as const;

export function writeBingAiPerformanceSnapshot(
  snapshot: BingAiPerformanceSnapshot,
  sourceScript: string,
) {
  const outputPath = resolve(process.cwd(), 'data', 'bing-ai-performance.json');
  writeFileSync(outputPath, `${JSON.stringify(snapshot, null, 2)}\n`);

  const protectedOutputPath = resolve(
    process.cwd(),
    'data',
    'seo-protected-pages.json',
  );
  const protectedPages = {
    generatedAt: snapshot.generatedAt,
    source: `Bing AI Performance cited pages plus manual strategic seeds. Generated by ${sourceScript}.`,
    pages: [
      ...snapshot.citedPages.map((page) => ({
        url: page.url,
        path: new URL(page.url).pathname,
        source: 'bing-ai-citation',
        reason: `Bing AI Performance cites this URL ${page.citations.toLocaleString()} times.`,
        citations: page.citations,
        clicks: page.clicks,
        impressions: page.impressions,
      })),
      ...MANUAL_SEEDS,
    ],
  };

  writeFileSync(
    protectedOutputPath,
    `${JSON.stringify(protectedPages, null, 2)}\n`,
  );

  return { outputPath, protectedOutputPath };
}
