import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { parseIsoDateOnly } from '@/lib/date-only';
import { getBirthChartShare } from '@/lib/share/birth-chart';
import {
  ShareBirthChartDisplayData,
  ShareBirthChartLayout,
} from '../ShareBirthChartLayout';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://lunary.app';

const formatDate = (value?: string) => {
  if (!value) return null;
  const parsed = parseIsoDateOnly(value);
  if (!parsed) return value;
  return new Intl.DateTimeFormat('en-US', { dateStyle: 'long' }).format(parsed);
};

const buildCanonical = (shareId: string) =>
  `${APP_URL}/share/birth-chart/${encodeURIComponent(shareId)}`;

const buildOgImageUrl = (shareId: string) =>
  `${APP_URL}/api/og/share/birth-chart?shareId=${encodeURIComponent(shareId)}`;

type ShareBirthChartSharePageProps = {
  params: Promise<{
    shareId: string;
  }>;
};

export async function generateMetadata({
  params,
}: ShareBirthChartSharePageProps): Promise<Metadata> {
  const resolvedParams = await params;
  const record = await getBirthChartShare(resolvedParams.shareId);
  if (!record) {
    notFound();
  }
  const placements = [
    record.sun ? `Sun ${record.sun}` : null,
    record.moon ? `Moon ${record.moon}` : null,
    record.rising ? `Rising ${record.rising}` : null,
  ]
    .filter(Boolean)
    .join(' · ');
  const insight = record.insight;
  const description =
    insight ||
    placements ||
    'Personalized birth chart insights generated by Lunary.';
  const title = record.name
    ? `${record.name}'s Birth Chart Highlights`
    : 'Birth Chart Highlights from Lunary';
  const canonical = buildCanonical(resolvedParams.shareId);
  const ogImage = buildOgImageUrl(resolvedParams.shareId);

  return {
    title,
    description,
    alternates: {
      canonical,
    },
    openGraph: {
      title,
      description,
      url: canonical,
      siteName: 'Lunary',
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}

export default async function ShareBirthChartSharePage({
  params,
}: ShareBirthChartSharePageProps) {
  const resolvedParams = await params;
  const record = await getBirthChartShare(resolvedParams.shareId);
  if (!record) {
    notFound();
  }

  const viewData: ShareBirthChartDisplayData = {
    name: record.name,
    formattedDate: formatDate(record.date),
    sun: record.sun,
    moon: record.moon,
    rising: record.rising,
    element: record.element,
    modality: record.modality,
    insight: record.insight,
    keywords: record.keywords ?? [],
    birthChart: record.placements,
  };

  return <ShareBirthChartLayout data={viewData} />;
}
