export const CHINESE_ANIMALS = [
  'rat',
  'ox',
  'tiger',
  'rabbit',
  'dragon',
  'snake',
  'horse',
  'goat',
  'monkey',
  'rooster',
  'dog',
  'pig',
] as const;

export type ChineseAnimal = (typeof CHINESE_ANIMALS)[number];

export interface ChineseZodiacData {
  animal: ChineseAnimal;
  displayName: string;
  emoji: string;
  element: string;
  yinYang: 'Yin' | 'Yang';
  years: number[];
  traits: string[];
  strengths: string[];
  weaknesses: string[];
  luckyNumbers: number[];
  luckyColors: string[];
  luckyFlowers: string[];
  compatibleWith: ChineseAnimal[];
  incompatibleWith: ChineseAnimal[];
  careerPaths: string[];
  famousPeople: string[];
}

export const CHINESE_ZODIAC_DATA: Record<ChineseAnimal, ChineseZodiacData> = {
  rat: {
    animal: 'rat',
    displayName: 'Rat',
    emoji: '🐀',
    element: 'Water',
    yinYang: 'Yang',
    years: [1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032],
    traits: [
      'quick-witted',
      'resourceful',
      'versatile',
      'kind',
      'smart',
      'charming',
    ],
    strengths: ['adaptability', 'cleverness', 'charm', 'thriftiness'],
    weaknesses: ['stubbornness', 'criticism of others', 'greed', 'gossip'],
    luckyNumbers: [2, 3],
    luckyColors: ['blue', 'gold', 'green'],
    luckyFlowers: ['lily', 'african violet'],
    compatibleWith: ['ox', 'dragon', 'monkey'],
    incompatibleWith: ['horse', 'rooster'],
    careerPaths: ['Writer', 'Director', 'Entrepreneur', 'Lawyer', 'Politician'],
    famousPeople: ['Shakespeare', 'Mozart', 'Prince Harry'],
  },
  ox: {
    animal: 'ox',
    displayName: 'Ox',
    emoji: '🐂',
    element: 'Earth',
    yinYang: 'Yin',
    years: [1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021, 2033],
    traits: [
      'diligent',
      'dependable',
      'strong',
      'determined',
      'honest',
      'patient',
    ],
    strengths: ['reliability', 'patience', 'methodical approach', 'strength'],
    weaknesses: [
      'stubbornness',
      'rigidity',
      'slow to change',
      'possessiveness',
    ],
    luckyNumbers: [1, 4],
    luckyColors: ['white', 'yellow', 'green'],
    luckyFlowers: ['tulip', 'peach blossom'],
    compatibleWith: ['rat', 'snake', 'rooster'],
    incompatibleWith: ['tiger', 'dragon', 'horse', 'goat'],
    careerPaths: [
      'Agriculture',
      'Manufacturing',
      'Military',
      'Medicine',
      'Banking',
    ],
    famousPeople: ['Barack Obama', 'Napoleon', 'Princess Diana'],
  },
  tiger: {
    animal: 'tiger',
    displayName: 'Tiger',
    emoji: '🐅',
    element: 'Wood',
    yinYang: 'Yang',
    years: [1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034],
    traits: [
      'brave',
      'confident',
      'competitive',
      'unpredictable',
      'charming',
      'authoritative',
    ],
    strengths: ['courage', 'enthusiasm', 'leadership', 'confidence'],
    weaknesses: ['arrogance', 'impulsiveness', 'restlessness', 'hot temper'],
    luckyNumbers: [1, 3, 4],
    luckyColors: ['blue', 'gray', 'orange'],
    luckyFlowers: ['cineraria', 'anthurium'],
    compatibleWith: ['dragon', 'horse', 'pig'],
    incompatibleWith: ['ox', 'tiger', 'snake', 'monkey'],
    careerPaths: ['Explorer', 'CEO', 'Politician', 'Military Leader', 'Actor'],
    famousPeople: ['Queen Elizabeth II', 'Tom Cruise', 'Lady Gaga'],
  },
  rabbit: {
    animal: 'rabbit',
    displayName: 'Rabbit',
    emoji: '🐇',
    element: 'Wood',
    yinYang: 'Yin',
    years: [1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035],
    traits: ['quiet', 'elegant', 'kind', 'responsible', 'patient', 'artistic'],
    strengths: ['diplomacy', 'sensitivity', 'compassion', 'artistic talent'],
    weaknesses: ['timidity', 'pessimism', 'over-cautiousness', 'escapism'],
    luckyNumbers: [3, 4, 6],
    luckyColors: ['red', 'pink', 'purple', 'blue'],
    luckyFlowers: ['plantain lily', 'jasmine'],
    compatibleWith: ['goat', 'monkey', 'dog', 'pig'],
    incompatibleWith: ['snake', 'rooster'],
    careerPaths: ['Diplomat', 'Artist', 'Writer', 'Counselor', 'Designer'],
    famousPeople: ['Albert Einstein', 'Michael Jordan', 'Lionel Messi'],
  },
  dragon: {
    animal: 'dragon',
    displayName: 'Dragon',
    emoji: '🐉',
    element: 'Earth',
    yinYang: 'Yang',
    years: [1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024, 2036],
    traits: [
      'confident',
      'intelligent',
      'ambitious',
      'charismatic',
      'powerful',
      'lucky',
    ],
    strengths: ['leadership', 'vision', 'power', 'good fortune'],
    weaknesses: ['arrogance', 'impatience', 'intolerance', 'unrealistic'],
    luckyNumbers: [1, 6, 7],
    luckyColors: ['gold', 'silver', 'gray'],
    luckyFlowers: ['bleeding heart', 'dragon flower'],
    compatibleWith: ['rooster', 'rat', 'monkey'],
    incompatibleWith: ['ox', 'goat', 'dog'],
    careerPaths: [
      'Entrepreneur',
      'Inventor',
      'Architect',
      'Lawyer',
      'Journalist',
    ],
    famousPeople: ['Bruce Lee', 'Rihanna', 'John Lennon'],
  },
  snake: {
    animal: 'snake',
    displayName: 'Snake',
    emoji: '🐍',
    element: 'Fire',
    yinYang: 'Yin',
    years: [1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025, 2037],
    traits: [
      'enigmatic',
      'intelligent',
      'wise',
      'graceful',
      'intuitive',
      'analytical',
    ],
    strengths: ['wisdom', 'intuition', 'sophistication', 'mystique'],
    weaknesses: ['jealousy', 'suspicion', 'coldness', 'manipulation'],
    luckyNumbers: [2, 8, 9],
    luckyColors: ['black', 'red', 'yellow'],
    luckyFlowers: ['orchid', 'cactus'],
    compatibleWith: ['dragon', 'rooster'],
    incompatibleWith: ['tiger', 'rabbit', 'snake', 'goat', 'pig'],
    careerPaths: [
      'Scientist',
      'Analyst',
      'Investigator',
      'Philosopher',
      'Fashion Designer',
    ],
    famousPeople: ['Taylor Swift', 'Oprah Winfrey', 'Pablo Picasso'],
  },
  horse: {
    animal: 'horse',
    displayName: 'Horse',
    emoji: '🐎',
    element: 'Fire',
    yinYang: 'Yang',
    years: [1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026, 2038],
    traits: [
      'animated',
      'active',
      'energetic',
      'warm-hearted',
      'intelligent',
      'able',
    ],
    strengths: ['energy', 'independence', 'charisma', 'quick-thinking'],
    weaknesses: ['impatience', 'selfishness', 'temper', 'irresponsibility'],
    luckyNumbers: [2, 3, 7],
    luckyColors: ['yellow', 'green'],
    luckyFlowers: ['calla lily', 'jasmine'],
    compatibleWith: ['tiger', 'goat', 'rabbit'],
    incompatibleWith: ['rat', 'ox', 'rooster'],
    careerPaths: ['Athlete', 'Pilot', 'Journalist', 'Sales', 'Tour Guide'],
    famousPeople: ['Paul McCartney', 'Jackie Chan', 'Emma Watson'],
  },
  goat: {
    animal: 'goat',
    displayName: 'Goat',
    emoji: '🐐',
    element: 'Earth',
    yinYang: 'Yin',
    years: [1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027, 2039],
    traits: [
      'calm',
      'gentle',
      'creative',
      'sympathetic',
      'amicable',
      'persevering',
    ],
    strengths: ['creativity', 'kindness', 'artistic talent', 'gentle nature'],
    weaknesses: ['indecisiveness', 'timidity', 'pessimism', 'dependency'],
    luckyNumbers: [2, 7],
    luckyColors: ['brown', 'red', 'purple'],
    luckyFlowers: ['carnation', 'primrose'],
    compatibleWith: ['rabbit', 'horse', 'pig'],
    incompatibleWith: ['ox', 'tiger', 'dog'],
    careerPaths: ['Artist', 'Musician', 'Designer', 'Florist', 'Pediatrician'],
    famousPeople: ['Steve Jobs', 'Michelangelo', 'Julia Roberts'],
  },
  monkey: {
    animal: 'monkey',
    displayName: 'Monkey',
    emoji: '🐒',
    element: 'Metal',
    yinYang: 'Yang',
    years: [1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028, 2040],
    traits: ['sharp', 'smart', 'curious', 'creative', 'playful', 'clever'],
    strengths: ['intelligence', 'versatility', 'wit', 'innovation'],
    weaknesses: ['jealousy', 'suspicion', 'arrogance', 'restlessness'],
    luckyNumbers: [4, 9],
    luckyColors: ['white', 'blue', 'gold'],
    luckyFlowers: ['chrysanthemum', 'allium'],
    compatibleWith: ['ox', 'rabbit'],
    incompatibleWith: ['tiger', 'pig'],
    careerPaths: ['Scientist', 'Engineer', 'Filmmaker', 'Trader', 'Jeweler'],
    famousPeople: ['Leonardo da Vinci', 'Will Smith', 'Selena Gomez'],
  },
  rooster: {
    animal: 'rooster',
    displayName: 'Rooster',
    emoji: '🐓',
    element: 'Metal',
    yinYang: 'Yin',
    years: [1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029, 2041],
    traits: [
      'observant',
      'hardworking',
      'courageous',
      'talented',
      'confident',
      'honest',
    ],
    strengths: ['honesty', 'energy', 'confidence', 'punctuality'],
    weaknesses: ['vanity', 'boastfulness', 'criticism', 'impatience'],
    luckyNumbers: [5, 7, 8],
    luckyColors: ['gold', 'brown', 'yellow'],
    luckyFlowers: ['gladiolus', 'impatiens'],
    compatibleWith: ['ox', 'snake'],
    incompatibleWith: ['rat', 'rabbit', 'horse', 'rooster', 'dog'],
    careerPaths: [
      'Soldier',
      'Firefighter',
      'Security Guard',
      'News Anchor',
      'Surgeon',
    ],
    famousPeople: ['Beyoncé', 'Roger Federer', 'Elton John'],
  },
  dog: {
    animal: 'dog',
    displayName: 'Dog',
    emoji: '🐕',
    element: 'Earth',
    yinYang: 'Yang',
    years: [1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030, 2042],
    traits: ['loyal', 'honest', 'amiable', 'kind', 'cautious', 'prudent'],
    strengths: ['loyalty', 'honesty', 'faithfulness', 'reliability'],
    weaknesses: ['stubbornness', 'cynicism', 'self-righteousness', 'anxiety'],
    luckyNumbers: [3, 4, 9],
    luckyColors: ['red', 'green', 'purple'],
    luckyFlowers: ['rose', 'cymbidium orchid'],
    compatibleWith: ['rabbit'],
    incompatibleWith: ['dragon', 'goat', 'rooster'],
    careerPaths: [
      'Judge',
      'Police Officer',
      'Scientist',
      'Counselor',
      'Professor',
    ],
    famousPeople: ['Winston Churchill', 'Madonna', 'Prince William'],
  },
  pig: {
    animal: 'pig',
    displayName: 'Pig',
    emoji: '🐷',
    element: 'Water',
    yinYang: 'Yin',
    years: [1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031, 2043],
    traits: [
      'compassionate',
      'generous',
      'diligent',
      'sincere',
      'sociable',
      'tolerant',
    ],
    strengths: ['generosity', 'diligence', 'compassion', 'concentration'],
    weaknesses: [
      'naivety',
      'over-reliance on others',
      'materialism',
      'laziness',
    ],
    luckyNumbers: [2, 5, 8],
    luckyColors: ['yellow', 'gray', 'brown', 'gold'],
    luckyFlowers: ['hydrangea', 'daisy'],
    compatibleWith: ['tiger', 'rabbit', 'goat'],
    incompatibleWith: ['snake', 'monkey'],
    careerPaths: ['Entertainer', 'Chef', 'Doctor', 'Veterinarian', 'Caterer'],
    famousPeople: ['Arnold Schwarzenegger', 'Hillary Clinton', 'Henry Ford'],
  },
};

export interface ChineseYearData {
  year: number;
  animal: ChineseAnimal;
  element: string;
  startDate: string;
  endDate: string;
  yinYang: 'Yin' | 'Yang';
}

export const CHINESE_YEARS: ChineseYearData[] = [
  {
    year: 2024,
    animal: 'dragon',
    element: 'Wood',
    startDate: 'Feb 10, 2024',
    endDate: 'Jan 28, 2025',
    yinYang: 'Yang',
  },
  {
    year: 2025,
    animal: 'snake',
    element: 'Wood',
    startDate: 'Jan 29, 2025',
    endDate: 'Feb 16, 2026',
    yinYang: 'Yin',
  },
  {
    year: 2026,
    animal: 'horse',
    element: 'Fire',
    startDate: 'Feb 17, 2026',
    endDate: 'Feb 5, 2027',
    yinYang: 'Yang',
  },
  {
    year: 2027,
    animal: 'goat',
    element: 'Fire',
    startDate: 'Feb 6, 2027',
    endDate: 'Jan 25, 2028',
    yinYang: 'Yin',
  },
  {
    year: 2028,
    animal: 'monkey',
    element: 'Earth',
    startDate: 'Jan 26, 2028',
    endDate: 'Feb 12, 2029',
    yinYang: 'Yang',
  },
  {
    year: 2029,
    animal: 'rooster',
    element: 'Earth',
    startDate: 'Feb 13, 2029',
    endDate: 'Feb 2, 2030',
    yinYang: 'Yin',
  },
  {
    year: 2030,
    animal: 'dog',
    element: 'Metal',
    startDate: 'Feb 3, 2030',
    endDate: 'Jan 22, 2031',
    yinYang: 'Yang',
  },
];

export function getChineseYearAnimal(year: number): ChineseAnimal {
  const baseYear = 1900;
  const offset = (year - baseYear) % 12;
  return CHINESE_ANIMALS[offset >= 0 ? offset : offset + 12];
}
