export const ZODIAC_SEASONS = [
  {
    sign: 'aries',
    displayName: 'Aries',
    symbol: '♈',
    element: 'Fire',
    startMonth: 3,
    startDay: 21,
    endMonth: 4,
    endDay: 19,
    season: 'Spring',
    theme: 'New beginnings, courage, and bold action',
    energy: 'Cardinal fire ignites new cycles and pioneering spirit',
    rituals: ['Set bold intentions', 'Start new projects', 'Physical activity'],
  },
  {
    sign: 'taurus',
    displayName: 'Taurus',
    symbol: '♉',
    element: 'Earth',
    startMonth: 4,
    startDay: 20,
    endMonth: 5,
    endDay: 20,
    season: 'Spring',
    theme: 'Stability, sensuality, and material grounding',
    energy: 'Fixed earth energy for building lasting foundations',
    rituals: ['Garden planting', 'Financial planning', 'Self-care practices'],
  },
  {
    sign: 'gemini',
    displayName: 'Gemini',
    symbol: '♊',
    element: 'Air',
    startMonth: 5,
    startDay: 21,
    endMonth: 6,
    endDay: 20,
    season: 'Spring/Summer',
    theme: 'Communication, learning, and social connections',
    energy: 'Mutable air brings mental agility and curiosity',
    rituals: ['Learn something new', 'Networking', 'Writing and journaling'],
  },
  {
    sign: 'cancer',
    displayName: 'Cancer',
    symbol: '♋',
    element: 'Water',
    startMonth: 6,
    startDay: 21,
    endMonth: 7,
    endDay: 22,
    season: 'Summer',
    theme: 'Home, family, and emotional nurturing',
    energy: 'Cardinal water initiates emotional depth and care',
    rituals: ['Home blessing', 'Family gatherings', 'Emotional healing'],
  },
  {
    sign: 'leo',
    displayName: 'Leo',
    symbol: '♌',
    element: 'Fire',
    startMonth: 7,
    startDay: 23,
    endMonth: 8,
    endDay: 22,
    season: 'Summer',
    theme: 'Creativity, self-expression, and joy',
    energy: 'Fixed fire radiates confidence and creative power',
    rituals: [
      'Creative projects',
      'Celebrate yourself',
      'Heart-opening practices',
    ],
  },
  {
    sign: 'virgo',
    displayName: 'Virgo',
    symbol: '♍',
    element: 'Earth',
    startMonth: 8,
    startDay: 23,
    endMonth: 9,
    endDay: 22,
    season: 'Summer/Fall',
    theme: 'Health, service, and practical organization',
    energy: 'Mutable earth refines and improves daily life',
    rituals: ['Health routines', 'Decluttering', 'Acts of service'],
  },
  {
    sign: 'libra',
    displayName: 'Libra',
    symbol: '♎',
    element: 'Air',
    startMonth: 9,
    startDay: 23,
    endMonth: 10,
    endDay: 22,
    season: 'Fall',
    theme: 'Balance, relationships, and harmony',
    energy: 'Cardinal air initiates partnerships and beauty',
    rituals: ['Relationship check-ins', 'Creating beauty', 'Finding balance'],
  },
  {
    sign: 'scorpio',
    displayName: 'Scorpio',
    symbol: '♏',
    element: 'Water',
    startMonth: 10,
    startDay: 23,
    endMonth: 11,
    endDay: 21,
    season: 'Fall',
    theme: 'Transformation, depth, and power',
    energy: 'Fixed water plumbs emotional depths and hidden truths',
    rituals: ['Shadow work', 'Ancestor connection', 'Release ceremonies'],
  },
  {
    sign: 'sagittarius',
    displayName: 'Sagittarius',
    symbol: '♐',
    element: 'Fire',
    startMonth: 11,
    startDay: 22,
    endMonth: 12,
    endDay: 21,
    season: 'Fall/Winter',
    theme: 'Adventure, philosophy, and expansion',
    energy: 'Mutable fire seeks truth and broader horizons',
    rituals: ['Travel planning', 'Learning philosophy', 'Vision questing'],
  },
  {
    sign: 'capricorn',
    displayName: 'Capricorn',
    symbol: '♑',
    element: 'Earth',
    startMonth: 12,
    startDay: 22,
    endMonth: 1,
    endDay: 19,
    season: 'Winter',
    theme: 'Ambition, structure, and legacy',
    energy: 'Cardinal earth builds lasting achievements',
    rituals: ['Goal setting', 'Career planning', 'Year-end reflection'],
  },
  {
    sign: 'aquarius',
    displayName: 'Aquarius',
    symbol: '♒',
    element: 'Air',
    startMonth: 1,
    startDay: 20,
    endMonth: 2,
    endDay: 18,
    season: 'Winter',
    theme: 'Innovation, community, and individuality',
    energy: 'Fixed air revolutionizes and connects humanity',
    rituals: [
      'Community service',
      'Innovation brainstorming',
      'Being authentically you',
    ],
  },
  {
    sign: 'pisces',
    displayName: 'Pisces',
    symbol: '♓',
    element: 'Water',
    startMonth: 2,
    startDay: 19,
    endMonth: 3,
    endDay: 20,
    season: 'Winter/Spring',
    theme: 'Dreams, spirituality, and transcendence',
    energy: 'Mutable water dissolves boundaries and connects to the divine',
    rituals: ['Dream journaling', 'Meditation', 'Artistic expression'],
  },
];

export function getSeasonDates(
  sign: string,
  year: number,
): { start: string; end: string } {
  const seasonData = ZODIAC_SEASONS.find((s) => s.sign === sign);
  if (!seasonData) return { start: '', end: '' };

  const startYear =
    seasonData.sign === 'capricorn' && seasonData.startMonth === 12
      ? year - 1
      : year;
  const endYear =
    seasonData.sign === 'capricorn' && seasonData.endMonth === 1 ? year : year;

  const months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];

  return {
    start: `${months[seasonData.startMonth - 1]} ${seasonData.startDay}, ${startYear}`,
    end: `${months[seasonData.endMonth - 1]} ${seasonData.endDay}, ${endYear}`,
  };
}
