import React from 'react';
import {
  AbsoluteFill,
  Audio,
  useCurrentFrame,
  useVideoConfig,
  staticFile,
} from 'remotion';
import { AnimatedBackground } from '../components/AnimatedBackground';
import { AnimatedSubtitles } from '../components/AnimatedSubtitles';
import { HookSequence } from '../components/HookSequence';
import { TopicCard } from '../components/TopicCard';
import { LowerThird } from '../components/LowerThird';
import { PersistentWatermark } from '../components/PersistentWatermark';
import { ProgressIndicator } from '../components/ProgressIndicator';
import { TransitionEffect } from '../components/TransitionEffect';
import { SymbolOverlay } from '../components/ZodiacSymbolOverlay';
import type { AudioSegment } from '../utils/timing';
import { secondsToFrames } from '../utils/timing';
import { detectCurrentTopic, isOutroSegment } from '../utils/topic-detection';
import type { CategoryVisualConfig } from '../config/category-visuals';
import { COLORS } from '../styles/theme';

export interface LongFormVideoProps {
  /** Title for the intro */
  title: string;
  /** Subtitle for intro (e.g., week dates) */
  subtitle?: string;
  /** Audio segments for subtitles with topic info */
  segments: AudioSegment[];
  /** Audio file URL */
  audioUrl?: string;
  /** Background music URL (optional) */
  backgroundMusicUrl?: string;
  /** Background images (with timestamps) */
  images?: Array<{
    url: string;
    startTime: number;
    endTime: number;
    topic?: string;
    item?: string;
  }>;
  /** Highlight terms for subtitles */
  highlightTerms?: string[];
  /** Show progress indicator */
  showProgress?: boolean;
  /** Lower third branding info */
  lowerThirdInfo?: {
    title: string;
    subtitle?: string;
  };
  /** Unique seed for generating different star positions and comet paths */
  seed?: string;
  /** Category visual configuration for themed backgrounds */
  categoryVisuals?: CategoryVisualConfig;
  /** Content for symbol detection (title + subtitle + segments) */
  symbolContent?: string;
}

/**
 * Long Form Video Composition (5-8 minutes)
 *
 * Optimized for YouTube
 * - Extended hook/intro sequence
 * - Topic cards for each section
 * - Lower third branding
 * - Animated subtitles throughout
 * - Image transitions between segments
 * - 16:9 aspect ratio (1920x1080)
 */
export const LongFormVideo: React.FC<LongFormVideoProps> = ({
  title,
  subtitle,
  segments,
  audioUrl,
  backgroundMusicUrl,
  images = [],
  highlightTerms = [],
  showProgress = true,
  lowerThirdInfo,
  seed = 'default',
  categoryVisuals,
  symbolContent,
}) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  // Calculate intro duration (first 5 seconds for long-form)
  const introDurationFrames = 150; // 5 seconds at 30fps
  const showIntro = frame < introDurationFrames;

  // Closing "Thank You" slide (last 4 seconds)
  const outroDurationFrames = 120; // 4 seconds at 30fps
  const outroStartFrame = durationInFrames - outroDurationFrames;
  const showOutro = frame >= outroStartFrame;

  // Real-time topic detection based on what's actually being spoken
  const currentTime = frame / fps;
  const detectedTopic = detectCurrentTopic(currentTime, segments);
  const isInOutro = isOutroSegment(currentTime, segments);

  // Fallback to image-based topics if no real-time detection
  let currentImage = images[0];
  if (images.length > 0) {
    for (let i = 0; i < images.length; i++) {
      if (
        currentTime >= images[i].startTime &&
        currentTime < images[i].endTime
      ) {
        currentImage = images[i];
        break;
      }
    }
  }

  // Use detected topic from subtitles, or fall back to image topic
  const currentTopic = detectedTopic || currentImage?.topic;

  // Only show symbols during specific topic segments (not intro or outro)
  const showSymbols = currentTopic && !showIntro && !showOutro;

  // Check if we're at a segment transition (first 3 seconds of new segment)
  const segmentStartFrame = currentImage
    ? secondsToFrames(currentImage.startTime, fps)
    : 0;
  const isAtSegmentStart =
    frame >= segmentStartFrame && frame < segmentStartFrame + 90; // Show for 3 seconds
  const showTopicCard =
    isAtSegmentStart &&
    currentImage?.topic &&
    frame > introDurationFrames &&
    !showOutro;

  // Show lower third periodically (every 90 seconds) for branding
  const showLowerThird =
    lowerThirdInfo &&
    frame > introDurationFrames &&
    frame % (90 * fps) < 120 && // Show for 4 seconds every 90 seconds
    frame < durationInFrames - 300; // Don't show in last 10 seconds

  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.cosmicBlack }}>
      {/* Animated background - fully generated by Remotion */}
      <AnimatedBackground
        showStars={true}
        seed={seed}
        animationType={categoryVisuals?.backgroundAnimation}
        particleTintColor={categoryVisuals?.particleTintColor}
        gradientColors={categoryVisuals?.gradientColors}
      />

      {/* Intro/Hook sequence with moon logo and branding */}
      {showIntro && (
        <HookSequence
          hookText={title}
          subtitle={subtitle}
          dateRange={
            subtitle
              ? subtitle.match(/(\w+ \d+)\s*-\s*(\w+ \d+)/)?.[0]
              : undefined
          }
          startFrame={0}
          durationFrames={introDurationFrames}
        />
      )}

      {/* Topic cards at segment transitions */}
      {showTopicCard && currentImage?.topic && (
        <TopicCard
          title={currentImage.topic}
          item={currentImage.item}
          startFrame={segmentStartFrame}
          position='top'
        />
      )}

      {/* Lower third branding */}
      {showLowerThird && lowerThirdInfo && (
        <LowerThird
          title={lowerThirdInfo.title}
          subtitle={lowerThirdInfo.subtitle}
          startFrame={
            Math.floor(frame / (90 * fps)) * (90 * fps) + introDurationFrames
          }
          durationFrames={120}
        />
      )}

      {/* Dynamic symbol overlay - appears only when discussing specific planets/events */}
      {showSymbols && currentTopic && (
        <SymbolOverlay content={currentTopic} opacity={0.25} fps={fps} />
      )}

      {/* Animated subtitles */}
      <AnimatedSubtitles
        segments={segments}
        highlightTerms={highlightTerms}
        highlightColor={categoryVisuals?.highlightColor}
        fontSize={36}
        bottomPosition={22}
        fps={fps}
      />

      {/* Main audio track */}
      {audioUrl && <Audio src={audioUrl} />}

      {/* Background music (lower volume) */}
      {backgroundMusicUrl && (
        <Audio
          src={
            backgroundMusicUrl.startsWith('/')
              ? staticFile(backgroundMusicUrl)
              : backgroundMusicUrl
          }
          volume={0.15}
        />
      )}

      {/* Persistent watermark throughout video */}
      <PersistentWatermark
        text='lunary.app'
        position='bottom-right'
        opacity={0.6}
        fps={fps}
      />

      {/* CTA overlay during outro speech - clean text only */}
      {isInOutro && !showIntro && (
        <div
          style={{
            position: 'absolute',
            top: '25%',
            left: '10%',
            right: '10%',
            textAlign: 'center',
            zIndex: 20,
          }}
        >
          <p
            style={{
              fontFamily: 'Roboto Mono, monospace',
              fontWeight: 600,
              fontSize: 48,
              color: COLORS.primaryText,
              margin: 0,
              marginBottom: '16px',
              letterSpacing: '-0.01em',
              textShadow:
                '0 0 40px rgba(0, 0, 0, 1), 0 4px 20px rgba(0, 0, 0, 0.9)',
            }}
          >
            Follow for more cosmic updates
          </p>
          <p
            style={{
              fontFamily: 'Roboto Mono, monospace',
              fontWeight: 400,
              fontSize: 28,
              color: '#8B7DFF',
              margin: 0,
              letterSpacing: 0,
              textShadow:
                '0 0 30px rgba(0, 0, 0, 1), 0 2px 12px rgba(0, 0, 0, 0.9)',
            }}
          >
            lunary.app
          </p>
        </div>
      )}

      {/* Progress indicator */}
      {showProgress && (
        <ProgressIndicator
          position='bottom'
          height={2}
          color={categoryVisuals?.accentColor}
        />
      )}

      {/* Fade out at end */}
      <TransitionEffect
        type='dissolve'
        startFrame={durationInFrames - 30}
        durationFrames={30}
        direction='out'
      />
    </AbsoluteFill>
  );
};

export default LongFormVideo;
