import type { Metadata } from 'next';
import { parseIsoDateOnly } from '@/lib/date-only';
import {
  ShareBirthChartDisplayData,
  ShareBirthChartLayout,
} from './ShareBirthChartLayout';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://lunary.app';

type ShareBirthChartSearchParams = {
  name?: string | string[];
  sun?: string | string[];
  moon?: string | string[];
  rising?: string | string[];
  element?: string | string[];
  modality?: string | string[];
  insight?: string | string[];
  keywords?: string | string[];
  date?: string | string[];
};

type ShareBirthChartPageProps = {
  searchParams?: Promise<ShareBirthChartSearchParams>;
};

const toStringParam = (value?: string | string[]) => {
  if (!value) return undefined;
  return Array.isArray(value) ? value[0] : value;
};

const truncate = (value?: string, limit = 160) => {
  if (!value) return undefined;
  if (value.length <= limit) return value;
  return `${value.slice(0, limit - 1).trimEnd()}…`;
};

const parseKeywords = (value?: string | string[]) => {
  const raw = toStringParam(value);
  if (!raw) return [];
  return raw
    .split(',')
    .map((keyword) => keyword.trim())
    .filter(Boolean)
    .slice(0, 5);
};

const buildOgImageUrl = (params: Record<string, string | undefined>) => {
  const search = new URLSearchParams();
  Object.entries(params).forEach(([key, value]) => {
    if (value) search.set(key, value);
  });
  return `${APP_URL}/api/og/share/birth-chart?${search.toString()}`;
};

export async function generateMetadata({
  searchParams,
}: ShareBirthChartPageProps): Promise<Metadata> {
  const resolved =
    (await (searchParams ?? Promise.resolve({}))) ?? ({} as const);
  const resolvedSearchParams = resolved as ShareBirthChartSearchParams;
  const name = toStringParam(resolvedSearchParams.name);
  const sun = toStringParam(resolvedSearchParams.sun);
  const moon = toStringParam(resolvedSearchParams.moon);
  const rising = toStringParam(resolvedSearchParams.rising);
  const element = toStringParam(resolvedSearchParams.element);
  const modality = toStringParam(resolvedSearchParams.modality);
  const insight = truncate(toStringParam(resolvedSearchParams.insight));
  const keywords = parseKeywords(resolvedSearchParams.keywords);
  const date = toStringParam(resolvedSearchParams.date);

  const placements = [
    sun ? `Sun ${sun}` : null,
    moon ? `Moon ${moon}` : null,
    rising ? `Rising ${rising}` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  const title = name
    ? `${name}'s Birth Chart Highlights`
    : 'Birth Chart Highlights from Lunary';

  const description =
    insight ||
    placements ||
    'Personalized birth chart insights generated by Lunary.';

  const ogImage = buildOgImageUrl({
    name: name ?? undefined,
    sun: sun ?? undefined,
    moon: moon ?? undefined,
    rising: rising ?? undefined,
    element: element ?? undefined,
    modality: modality ?? undefined,
    insight: insight ?? undefined,
  });

  const canonicalParams = new URLSearchParams();
  if (name) canonicalParams.set('name', name);
  if (sun) canonicalParams.set('sun', sun);
  if (moon) canonicalParams.set('moon', moon);
  if (rising) canonicalParams.set('rising', rising);
  if (element) canonicalParams.set('element', element);
  if (modality) canonicalParams.set('modality', modality);
  if (insight) canonicalParams.set('insight', insight);
  if (keywords.length) canonicalParams.set('keywords', keywords.join(','));
  if (date) canonicalParams.set('date', date);

  const canonical = `${APP_URL}/share/birth-chart${
    canonicalParams.toString() ? `?${canonicalParams.toString()}` : ''
  }`;

  return {
    title,
    description,
    alternates: {
      canonical,
    },
    openGraph: {
      title,
      description,
      url: canonical,
      siteName: 'Lunary',
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}

export default async function ShareBirthChartPage({
  searchParams,
}: ShareBirthChartPageProps) {
  const resolved =
    (await (searchParams ?? Promise.resolve({}))) ?? ({} as const);
  const resolvedSearchParams = resolved as ShareBirthChartSearchParams;
  const name = toStringParam(resolvedSearchParams.name);
  const sun = toStringParam(resolvedSearchParams.sun);
  const moon = toStringParam(resolvedSearchParams.moon);
  const rising = toStringParam(resolvedSearchParams.rising);
  const element = toStringParam(resolvedSearchParams.element);
  const modality = toStringParam(resolvedSearchParams.modality);
  const insight = truncate(toStringParam(resolvedSearchParams.insight));
  const keywords = parseKeywords(resolvedSearchParams.keywords);
  const date = toStringParam(resolvedSearchParams.date);
  const formattedDate = (() => {
    if (!date) return null;
    const parsed = parseIsoDateOnly(date);
    if (!parsed) return date;
    return new Intl.DateTimeFormat('en-US', { dateStyle: 'long' }).format(
      parsed,
    );
  })();

  const viewData: ShareBirthChartDisplayData = {
    name,
    formattedDate,
    sun,
    moon,
    rising,
    element,
    modality,
    insight,
    keywords,
  };

  return <ShareBirthChartLayout data={viewData} />;
}
