import type { Metadata } from 'next';
import Link from 'next/link';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://lunary.app';

type ShareBirthChartSearchParams = {
  name?: string | string[];
  sun?: string | string[];
  moon?: string | string[];
  rising?: string | string[];
  element?: string | string[];
  modality?: string | string[];
  insight?: string | string[];
  keywords?: string | string[];
  date?: string | string[];
};

type ShareBirthChartPageProps = {
  searchParams?: Promise<ShareBirthChartSearchParams>;
};

const toStringParam = (value?: string | string[]) => {
  if (!value) return undefined;
  return Array.isArray(value) ? value[0] : value;
};

const truncate = (value?: string, limit = 160) => {
  if (!value) return undefined;
  if (value.length <= limit) return value;
  return `${value.slice(0, limit - 1).trimEnd()}…`;
};

const parseKeywords = (value?: string | string[]) => {
  const raw = toStringParam(value);
  if (!raw) return [];
  return raw
    .split(',')
    .map((keyword) => keyword.trim())
    .filter(Boolean)
    .slice(0, 5);
};

const buildOgImageUrl = (params: Record<string, string | undefined>) => {
  const search = new URLSearchParams();
  Object.entries(params).forEach(([key, value]) => {
    if (value) search.set(key, value);
  });
  return `${APP_URL}/api/og/share/birth-chart?${search.toString()}`;
};

export async function generateMetadata({
  searchParams,
}: ShareBirthChartPageProps): Promise<Metadata> {
  const resolved =
    (await (searchParams ?? Promise.resolve({}))) ?? ({} as const);
  const resolvedSearchParams = resolved as ShareBirthChartSearchParams;
  const name = toStringParam(resolvedSearchParams.name);
  const sun = toStringParam(resolvedSearchParams.sun);
  const moon = toStringParam(resolvedSearchParams.moon);
  const rising = toStringParam(resolvedSearchParams.rising);
  const element = toStringParam(resolvedSearchParams.element);
  const modality = toStringParam(resolvedSearchParams.modality);
  const insight = truncate(toStringParam(resolvedSearchParams.insight));
  const keywords = parseKeywords(resolvedSearchParams.keywords);
  const date = toStringParam(resolvedSearchParams.date);

  const placements = [
    sun ? `Sun ${sun}` : null,
    moon ? `Moon ${moon}` : null,
    rising ? `Rising ${rising}` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  const title = name
    ? `${name}'s Birth Chart Highlights`
    : 'Birth Chart Highlights from Lunary';

  const description =
    insight ||
    placements ||
    'Personalized birth chart insights generated by Lunary.';

  const ogImage = buildOgImageUrl({
    name: name ?? undefined,
    sun: sun ?? undefined,
    moon: moon ?? undefined,
    rising: rising ?? undefined,
    element: element ?? undefined,
    modality: modality ?? undefined,
    insight: insight ?? undefined,
  });

  const canonicalParams = new URLSearchParams();
  if (name) canonicalParams.set('name', name);
  if (sun) canonicalParams.set('sun', sun);
  if (moon) canonicalParams.set('moon', moon);
  if (rising) canonicalParams.set('rising', rising);
  if (element) canonicalParams.set('element', element);
  if (modality) canonicalParams.set('modality', modality);
  if (insight) canonicalParams.set('insight', insight);
  if (keywords.length) canonicalParams.set('keywords', keywords.join(','));
  if (date) canonicalParams.set('date', date);

  const canonical = `${APP_URL}/share/birth-chart${
    canonicalParams.toString() ? `?${canonicalParams.toString()}` : ''
  }`;

  return {
    title,
    description,
    alternates: {
      canonical,
    },
    openGraph: {
      title,
      description,
      url: canonical,
      siteName: 'Lunary',
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}

export default async function ShareBirthChartPage({
  searchParams,
}: ShareBirthChartPageProps) {
  const resolved =
    (await (searchParams ?? Promise.resolve({}))) ?? ({} as const);
  const resolvedSearchParams = resolved as ShareBirthChartSearchParams;
  const name = toStringParam(resolvedSearchParams.name);
  const sun = toStringParam(resolvedSearchParams.sun);
  const moon = toStringParam(resolvedSearchParams.moon);
  const rising = toStringParam(resolvedSearchParams.rising);
  const element = toStringParam(resolvedSearchParams.element);
  const modality = toStringParam(resolvedSearchParams.modality);
  const insight = truncate(toStringParam(resolvedSearchParams.insight));
  const keywords = parseKeywords(resolvedSearchParams.keywords);
  const date = toStringParam(resolvedSearchParams.date);

  return (
    <div className='min-h-screen w-full bg-gradient-to-br from-zinc-950 via-blue-950 to-indigo-900 text-white'>
      <div className='mx-auto flex min-h-screen max-w-4xl flex-col items-center px-4 py-16 text-center sm:px-6 lg:px-8'>
        <div className='w-full rounded-3xl border border-white/10 bg-black/40 p-8 shadow-2xl backdrop-blur'>
          <p className='text-xs uppercase tracking-[0.35em] text-lunary-secondary-200'>
            Shared from Lunary
          </p>
          <h1 className='mt-6 text-2xl font-light text-white sm:text-3xl'>
            {name
              ? `${name}'s Birth Chart Highlights`
              : 'Birth Chart Highlights'}
          </h1>
          <p className='mt-2 text-sm text-lunary-secondary-200'>
            {date
              ? `Generated for ${new Date(date).toLocaleDateString('en-US')}`
              : 'Personalized cosmic profile'}
          </p>

          <div className='mt-10 grid gap-4 sm:grid-cols-3'>
            <div className='rounded-2xl border border-lunary-secondary-700 bg-lunary-secondary-950 p-4'>
              <p className='text-[0.7rem] uppercase tracking-[0.3em] text-lunary-secondary-100'>
                Sun
              </p>
              <p className='mt-2 text-xl font-light text-white'>{sun ?? '—'}</p>
            </div>
            <div className='rounded-2xl border border-lunary-primary-700 bg-lunary-primary-900/10 p-4'>
              <p className='text-[0.7rem] uppercase tracking-[0.3em] text-lunary-primary-100/70'>
                Moon
              </p>
              <p className='mt-2 text-xl font-light text-white'>
                {moon ?? '—'}
              </p>
            </div>
            <div className='rounded-2xl border border-lunary-primary-700 bg-lunary-primary-950 p-4'>
              <p className='text-[0.7rem] uppercase tracking-[0.3em] text-lunary-primary-100'>
                Rising
              </p>
              <p className='mt-2 text-xl font-light text-white'>
                {rising ?? '—'}
              </p>
            </div>
          </div>

          <div className='mt-8 grid gap-4 sm:grid-cols-2'>
            <div className='rounded-2xl border border-lunary-success-700 bg-lunary-success-950 p-4'>
              <p className='text-[0.65rem] uppercase tracking-[0.3em] text-lunary-success-100'>
                Dominant Element
              </p>
              <p className='mt-2 text-lg font-light text-white'>
                {element ?? 'Balanced'}
              </p>
            </div>
            <div className='rounded-2xl border border-lunary-accent-700 bg-lunary-accent-950 p-4'>
              <p className='text-[0.65rem] uppercase tracking-[0.3em] text-lunary-accent-100'>
                Core Modality
              </p>
              <p className='mt-2 text-lg font-light text-white'>
                {modality ?? 'Dynamic'}
              </p>
            </div>
          </div>

          {keywords.length > 0 && (
            <div className='mt-6 flex flex-wrap justify-center gap-2 text-xs text-lunary-secondary-100'>
              {keywords.map((keyword) => (
                <span
                  key={keyword}
                  className='rounded-full border border-lunary-secondary-600 px-3 py-1'
                >
                  {keyword}
                </span>
              ))}
            </div>
          )}

          {insight && (
            <div className='mt-8 rounded-2xl border border-white/10 bg-white/5 p-6 text-left'>
              <p className='text-sm font-semibold text-lunary-secondary-100 uppercase tracking-[0.3em] mb-2'>
                Signature Insight
              </p>
              <p className='text-sm leading-relaxed text-zinc-100/90'>
                {insight}
              </p>
            </div>
          )}

          <div className='mt-12 space-y-4 text-sm text-zinc-200/80'>
            <p>
              Your birth chart is a cosmic snapshot of the skies when you were
              born. Lunary combines real astronomical data with modern guidance
              to surface the placements and patterns that define your path.
            </p>
            <p>
              Ready to explore your chart in depth? Generate detailed planetary
              insights, pattern analysis, and guidance tailored to your cosmic
              blueprint.
            </p>
          </div>

          <div className='mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center'>
            <Link
              href='/birth-chart'
              className='inline-flex items-center rounded-full bg-lunary-primary px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-lunary-primary-800 transition hover:bg-lunary-primary-400'
            >
              Explore your birth chart on Lunary
            </Link>
            <Link
              href='/'
              className='text-sm font-medium text-lunary-secondary-200 transition hover:text-lunary-secondary-100'
            >
              Discover more cosmic tools →
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
