/**
 * Audit Stripe shop products and optionally archive dead-weight ones.
 *
 * A product is "dead weight" if it has a `purchaseType` of `moon_pack` in
 * metadata, OR if its slug doesn't match any local generator entry
 * (meaning it was auto-generated by the now-disabled cron).
 *
 * Usage:
 *   # List all products grouped by category (dry-run)
 *   npx tsx scripts/audit-stripe-shop.ts
 *
 *   # Archive products with no local entry (dead-weight cron products)
 *   npx tsx scripts/audit-stripe-shop.ts --archive-dead-weight
 *
 *   # Archive a specific product by slug
 *   npx tsx scripts/audit-stripe-shop.ts --archive slug-name
 *
 * Requires STRIPE_SECRET_KEY in env.
 */

import Stripe from 'stripe';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.join(__dirname, '../.env.local') });

// Local slugs that exist in the generators — anything NOT in this list is dead weight.
// Built by running the generators statically (slug-only, no DB needed).
// Add/remove slugs here as the generators evolve.
import { getAllProducts } from '../src/lib/shop/generators';

function getStripe() {
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) throw new Error('STRIPE_SECRET_KEY not set');
  return new Stripe(key);
}

type StripeProduct = Stripe.Product & {
  priceCents?: number | null;
  priceId?: string | null;
};

async function fetchAllActiveProducts(
  stripe: Stripe,
): Promise<StripeProduct[]> {
  const products: Stripe.Product[] = [];
  for await (const p of stripe.products.list({
    limit: 100,
    active: true,
    expand: ['data.default_price'],
  })) {
    products.push(p);
  }
  return products as StripeProduct[];
}

function getPrice(product: Stripe.Product): {
  cents: number | null;
  priceId: string | null;
} {
  const dp = product.default_price;
  if (!dp) return { cents: null, priceId: null };
  if (typeof dp === 'string') return { cents: null, priceId: dp };
  return {
    cents: (dp as Stripe.Price).unit_amount ?? null,
    priceId: (dp as Stripe.Price).id,
  };
}

async function main() {
  const args = process.argv.slice(2);
  const archiveDeadWeight = args.includes('--archive-dead-weight');
  const archiveSlug = args.includes('--archive')
    ? args[args.indexOf('--archive') + 1]
    : null;

  const stripe = getStripe();
  const stripeProducts = await fetchAllActiveProducts(stripe);

  // Local slugs from generators
  const localProducts = getAllProducts();
  const localSlugs = new Set(localProducts.map((p) => p.slug));

  // Filter to shop products (have a slug in metadata)
  const shopProducts = stripeProducts.filter((p) => !!p.metadata?.slug);
  const nonShopProducts = stripeProducts.filter((p) => !p.metadata?.slug);

  // Classify
  const live: StripeProduct[] = [];
  const deadWeight: StripeProduct[] = [];

  for (const p of shopProducts) {
    const slug = p.metadata.slug;
    const isMoonPack =
      p.metadata?.purchaseType === 'moon_pack' ||
      slug?.includes('moon-') ||
      slug?.includes('-moon');
    const hasLocal = localSlugs.has(slug);

    if (!hasLocal || isMoonPack) {
      deadWeight.push(p);
    } else {
      live.push(p);
    }
  }

  // Group live products by category
  const byCategory = new Map<string, StripeProduct[]>();
  for (const p of live) {
    const cat = p.metadata?.category || 'unknown';
    byCategory.set(cat, [...(byCategory.get(cat) || []), p]);
  }

  console.log('\n══════════════════════════════════════════════════');
  console.log('  LUNARY STRIPE SHOP AUDIT');
  console.log('══════════════════════════════════════════════════\n');

  console.log(`  Total Stripe active products:  ${stripeProducts.length}`);
  console.log(`  Non-shop products (no slug):   ${nonShopProducts.length}`);
  console.log(`  Shop products:                 ${shopProducts.length}`);
  console.log(`  ✅  Live (match local):         ${live.length}`);
  console.log(`  🗑️   Dead weight (no local):    ${deadWeight.length}`);

  console.log('\n── LIVE PRODUCTS BY CATEGORY ─────────────────────\n');
  const sortedCats = [...byCategory.entries()].sort(
    (a, b) => b[1].length - a[1].length,
  );
  for (const [cat, products] of sortedCats) {
    console.log(`  ${cat.padEnd(20)} ${products.length} products`);
    for (const p of products) {
      const { cents } = getPrice(p);
      const price = cents ? `£${(cents / 100).toFixed(2)}` : 'no price';
      console.log(
        `    • ${p.metadata.slug.padEnd(45)} ${price.padStart(8)}  (${p.id})`,
      );
    }
    console.log('');
  }

  if (deadWeight.length > 0) {
    console.log('── DEAD WEIGHT (to archive) ───────────────────────\n');
    for (const p of deadWeight) {
      const { cents } = getPrice(p);
      const price = cents ? `£${(cents / 100).toFixed(2)}` : 'no price';
      const reason = !localSlugs.has(p.metadata.slug)
        ? 'no local entry'
        : 'moon pack';
      console.log(
        `  🗑️  ${p.metadata.slug.padEnd(45)} ${price.padStart(8)}  [${reason}]  (${p.id})`,
      );
    }
    console.log('');
  }

  // Archive dead weight if requested
  if (archiveDeadWeight && deadWeight.length > 0) {
    console.log(
      `\n── ARCHIVING ${deadWeight.length} DEAD WEIGHT PRODUCTS ─────────────\n`,
    );
    for (const p of deadWeight) {
      await stripe.products.update(p.id, { active: false });
      console.log(`  ✅  Archived: ${p.metadata.slug} (${p.id})`);
    }
    console.log('\n  Done. Reload the shop to confirm.\n');
  } else if (archiveDeadWeight && deadWeight.length === 0) {
    console.log('\n  Nothing to archive — shop is clean.\n');
  }

  // Archive a specific slug
  if (archiveSlug) {
    const target = shopProducts.find((p) => p.metadata.slug === archiveSlug);
    if (!target) {
      console.error(
        `\n  ❌  No active Stripe product found with slug: ${archiveSlug}\n`,
      );
      process.exit(1);
    }
    await stripe.products.update(target.id, { active: false });
    console.log(`\n  ✅  Archived: ${archiveSlug} (${target.id})\n`);
  }

  if (!archiveDeadWeight && !archiveSlug) {
    console.log(
      '  Run with --archive-dead-weight to archive all dead-weight products.',
    );
    console.log('  Run with --archive <slug> to archive a specific product.\n');
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
