import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import {
  getBingBacklinkPages,
  getBingTopPages,
} from '../src/lib/bing/webmaster';
import { normalizeProtectedSeoUrl } from '../src/lib/seo/protected-pages';

type ProtectedPageDraft = {
  url: string;
  path: string;
  source: 'bing-page' | 'bing-backlink' | 'manual';
  reason: string;
  clicks?: number;
  impressions?: number;
  backlinks?: number;
};

const manualProtectedPages: ProtectedPageDraft[] = [
  {
    url: 'https://lunary.app/grimoire',
    path: '/grimoire',
    source: 'manual',
    reason:
      'Manual seed: core astrology knowledge hub for search and AI discovery.',
  },
  {
    url: 'https://lunary.app/grimoire/guides/birth-chart-complete-guide',
    path: '/grimoire/guides/birth-chart-complete-guide',
    source: 'manual',
    reason:
      'Manual seed: deep evergreen birth chart guide with strong AI citation potential.',
  },
  {
    url: 'https://lunary.app/grimoire/guides/tarot-complete-guide',
    path: '/grimoire/guides/tarot-complete-guide',
    source: 'manual',
    reason:
      'Manual seed: deep evergreen tarot guide with strong AI citation potential.',
  },
  {
    url: 'https://lunary.app/grimoire/guides/moon-phases-guide',
    path: '/grimoire/guides/moon-phases-guide',
    source: 'manual',
    reason:
      'Manual seed: deep evergreen moon phases guide with strong AI citation potential.',
  },
];

const outputPath = resolve(process.cwd(), 'data', 'seo-protected-pages.json');
const now = new Date();
const endDate = now.toISOString().slice(0, 10);
const startDate = new Date(now);
startDate.setDate(startDate.getDate() - 90);
const startDateString = startDate.toISOString().slice(0, 10);

const minClicks = Number(process.env.BING_PROTECTED_MIN_CLICKS || 1);
const minImpressions = Number(process.env.BING_PROTECTED_MIN_IMPRESSIONS || 25);
const minBacklinks = Number(process.env.BING_PROTECTED_MIN_BACKLINKS || 1);
const pageLimit = Number(process.env.BING_PROTECTED_PAGE_LIMIT || 250);
const backlinkLimit = Number(process.env.BING_PROTECTED_BACKLINK_LIMIT || 250);

function upsertPage(
  map: Map<string, ProtectedPageDraft>,
  draft: ProtectedPageDraft,
) {
  const existing = map.get(draft.url);
  if (!existing) {
    map.set(draft.url, draft);
    return;
  }

  map.set(draft.url, {
    ...existing,
    source: existing.source === 'bing-page' ? existing.source : draft.source,
    reason: [existing.reason, draft.reason].filter(Boolean).join(' '),
    clicks: Math.max(existing.clicks || 0, draft.clicks || 0) || undefined,
    impressions:
      Math.max(existing.impressions || 0, draft.impressions || 0) || undefined,
    backlinks:
      Math.max(existing.backlinks || 0, draft.backlinks || 0) || undefined,
  });
}

async function main() {
  const [topPages, backlinkPages] = await Promise.all([
    getBingTopPages(startDateString, endDate, pageLimit),
    getBingBacklinkPages(undefined, backlinkLimit),
  ]);

  const protectedPages = new Map<string, ProtectedPageDraft>();

  for (const page of manualProtectedPages) {
    upsertPage(protectedPages, page);
  }

  for (const page of topPages) {
    if (page.clicks < minClicks && page.impressions < minImpressions) continue;

    const url = normalizeProtectedSeoUrl(page.page);
    if (!url) continue;

    upsertPage(protectedPages, {
      url,
      path: new URL(url).pathname,
      source: 'bing-page',
      reason: `Bing page performance in the last 90 days: ${page.clicks} clicks, ${page.impressions} impressions.`,
      clicks: page.clicks,
      impressions: page.impressions,
    });
  }

  for (const page of backlinkPages) {
    if (page.count < minBacklinks) continue;

    const url = normalizeProtectedSeoUrl(page.url);
    if (!url) continue;

    upsertPage(protectedPages, {
      url,
      path: new URL(url).pathname,
      source: 'bing-backlink',
      reason: `Bing reports ${page.count} backlinks to this URL.`,
      backlinks: page.count,
    });
  }

  const pages = Array.from(protectedPages.values()).sort(
    (a, b) =>
      (b.clicks || 0) - (a.clicks || 0) ||
      (b.impressions || 0) - (a.impressions || 0) ||
      (b.backlinks || 0) - (a.backlinks || 0) ||
      a.path.localeCompare(b.path),
  );

  const manifest = {
    generatedAt: now.toISOString(),
    source:
      'Bing Webmaster page performance and backlink data. Generated by scripts/sync-bing-seo-protected-pages.ts.',
    dateRange: {
      startDate: startDateString,
      endDate,
    },
    thresholds: {
      minClicks,
      minImpressions,
      minBacklinks,
    },
    pages,
  };

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${JSON.stringify(manifest, null, 2)}\n`);

  console.log(
    `Protected ${pages.length} Bing-performing SEO pages in ${outputPath}`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
